### ISSUE TITLE
`set` callback on an object array

### ISSUE THREAD

**Issue by RoyRao2333** [DawidWraga/davstack#12]
I found that it can use callbacks on primitives:

<img width="866" alt="image" src="https://github.com/user-attachments/assets/f8a54db3-b355-46fe-ab94-58dce35a7cb4">

But when I tried to use callbacks on an object array, nothing happens and the store is not updating:

```ts
myStore.someList.set((prev) => {
  return [...prev, { id: 'xxx', title: 'yyy' }];
});
```

How to fix this or am I doing this wrong? Thanks!

**Comment by Feidorian** [comment]
@RoyRao2333  The type of the set callback argument matters; when it's an array/object, modify the draft directly and return nothing, and when its a primitive, return the new value/state. [Documentation Reference](https://www.davstack.com/store/updating-state).

**Comment by RoyRao2333** [comment]
@Feidorian 

Yes, It's working now. Thanks a lot!
